/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package claudiu.test;

import claudiu.MasinaTunsIarba;
import claudiu.Motosapa;
import comun.Aparat;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.StringTokenizer;

/**
 *
 * @author cc642
 */
public class ClaudiuGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClaudiuGUI
     */
    public ClaudiuGUI() {
        //initVectorAparate();
        //initVectorMasinaTunsIarba();
        //initVectorMotosapa();
        initCei3VectoriDinFisier("src/test/java/claudiu/test/aparate.txt");
        initComponents();
        afiseazaVectoriiCitit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputTipAlimentareMTI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputVolumCosColector = new javax.swing.JTextField();
        buttonMTI = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        afisareText = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputGreutateMotosapa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputTipPornireMotosapa = new javax.swing.JTextField();
        buttonMotosapa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        afisareText2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputGreutateAparat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inputPretAparat = new javax.swing.JTextField();
        buttonAparat = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        afisareText3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        afisareText6 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        afisareText4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        afisareText5 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selectare masini tuns iarba");

        jLabel2.setText("Introduceti tipul de alimentare:");

        inputTipAlimentareMTI.setToolTipText("ex:Benzina");

        jLabel3.setText("Introduceti volumul cosului colector:");

        inputVolumCosColector.setToolTipText("ex:60");

        buttonMTI.setText("Afiseaza masinile");
        buttonMTI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonMTI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMTIMouseClicked(evt);
            }
        });

        afisareText.setColumns(20);
        afisareText.setRows(5);
        jScrollPane1.setViewportView(afisareText);

        jLabel4.setText("Selectare motosape");

        jLabel5.setText("Introduceti greutatea:");

        inputGreutateMotosapa.setToolTipText("ex:30");

        jLabel6.setText("Introduceti tipul de pornire:");
        jLabel6.setToolTipText("");

        inputTipPornireMotosapa.setToolTipText("ex:Manuala");

        buttonMotosapa.setText("Afiseaza motosapele");
        buttonMotosapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMotosapaMouseClicked(evt);
            }
        });

        afisareText2.setColumns(20);
        afisareText2.setRows(5);
        jScrollPane2.setViewportView(afisareText2);

        jLabel7.setText("Selectare aparate");

        jLabel8.setText("Introduceti greutatea:");

        inputGreutateAparat.setToolTipText("ex:15");

        jLabel9.setText("Introduceti pretul");
        jLabel9.setToolTipText("");

        inputPretAparat.setToolTipText("ex2500");

        buttonAparat.setText("Afiseaza aparatele");
        buttonAparat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAparatMouseClicked(evt);
            }
        });

        afisareText3.setColumns(20);
        afisareText3.setRows(5);
        jScrollPane3.setViewportView(afisareText3);

        afisareText6.setColumns(20);
        afisareText6.setRows(5);
        jScrollPane4.setViewportView(afisareText6);

        afisareText4.setColumns(20);
        afisareText4.setRows(5);
        jScrollPane5.setViewportView(afisareText4);

        afisareText5.setColumns(20);
        afisareText5.setRows(5);
        jScrollPane6.setViewportView(afisareText5);

        jLabel10.setText("Aparate:");

        jLabel11.setText("Masini de tuns iarba:");

        jLabel12.setText("Motosape");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(inputTipAlimentareMTI, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(inputVolumCosColector, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMTI)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(buttonMotosapa)
                    .addComponent(inputGreutateMotosapa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTipPornireMotosapa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(inputGreutateAparat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(inputPretAparat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAparat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(234, 234, 234)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputGreutateMotosapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputTipPornireMotosapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonMotosapa))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputTipAlimentareMTI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputVolumCosColector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonMTI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputGreutateAparat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputPretAparat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonAparat))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5)
                                    .addComponent(jScrollPane6))))
                        .addGap(63, 63, 63))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMTIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMTIMouseClicked
        // TODO add your handling code here:
        try{
        String s = "";
        String tipAlimen = inputTipAlimentareMTI.getText();
        float volumCC = Float.parseFloat(inputVolumCosColector.getText());
        for(int i = 0 ; i < v.length ; i++){
            if(v[i].getTipAlimentare().compareTo(tipAlimen) == 0 && v[i].getVolumCosColector() <= volumCC)
                s=s+v[i]+'\n';
        }
        afisareText.setText(s);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Eroare campuri introduse pentru masinile de tuns iarba", "Error",JOptionPane.ERROR_MESSAGE);
            System.out.println("eroare la input masina tuns iarba");
        }
    }//GEN-LAST:event_buttonMTIMouseClicked

    private void buttonMotosapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMotosapaMouseClicked
        // TODO add your handling code here:
        try{
        String s = "";
        String tipPornire = inputTipPornireMotosapa.getText();
        float greutate = Float.parseFloat(inputGreutateMotosapa.getText());
        for(int i = 0 ; i < u.length ; i++){
            if(u[i].getGreutate() <= greutate && u[i].getTipPornire().compareTo(tipPornire) == 0)
                s=s+u[i]+'\n';
        }
        afisareText2.setText(s);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Eroare campuri introduse pentru motosapa", "Error",JOptionPane.ERROR_MESSAGE);
            System.out.println("eroare la input motosapa");
        }
    }//GEN-LAST:event_buttonMotosapaMouseClicked

    private void buttonAparatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAparatMouseClicked
        // TODO add your handling code here:
        try{
        String s = "";
        float pret = Float.parseFloat(inputPretAparat.getText());
        float greutate = Float.parseFloat(inputGreutateAparat.getText());
        for(int i = 0 ; i < aparate.length ; i++){
            if(aparate[i].getGreutate() <= greutate && aparate[i].getPret() <= pret)
                s=s+aparate[i]+'\n';
        }
        afisareText3.setText(s);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Eroare campuri introduse pentru aparat", "Error",JOptionPane.ERROR_MESSAGE);
            System.out.println("eroare la input aparate");
        }
    }//GEN-LAST:event_buttonAparatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaudiuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaudiuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaudiuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaudiuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaudiuGUI().setVisible(true);
            }
        });
    }
    
    private void initVectorAparate(){
        aparate[0] = new Aparat("Honda", "HRX2VKA", 2500, "Verde", 42);
        aparate[1] = new Aparat("Bosch", "Rotak 4", 400, "Verde", 6.8f);
        aparate[2] = new Aparat("Husqvarna", "LC 33", 3900, "Portocaliu", 26);
        aparate[3] = new Aparat("Makita", "DLM", 2400, "Albastru", 15);
        aparate[4] = new Aparat("Stihl", "RMA 4", 1300, "Alb cu portocaliu", 21);
        aparate[5] = new Aparat("Greenworks", "GGX1", 1500, "Verde", 18);
        aparate[6] = new Aparat("AL-KO", "Classic 4.66", 2700, "Roșu cu negru", 27);
        aparate[7] = new Aparat("Einhell", "GE-CM 36/47", 1000, "Roșu cu negru", 25);
        aparate[8] = new Aparat("Flymo", "Hover", 1600, "Portocaliu cu gri", 5.5f);
        aparate[9] = new Aparat("Wolf-Garten", "A 120", 2000, "Roșu cu galben", 35);
    }
    
    private void initVectorMasinaTunsIarba(){
        v[0] = new MasinaTunsIarba("Honda", "HRX217VKA", 3500, "Rosu", 42, "Benzina", "Otel inoxidabil", 5.5f, 53, 7, 70  );
        v[1] = new MasinaTunsIarba("Bosch", "Rotak 32", 800, "Verde", 6.8f, "Electrica", "Otel calit", 1200, 32, 3, 31);
        v[2] = new MasinaTunsIarba("Husqvarna", "LC 140S", 1900, "Portocaliu", 26, "Benzina", "Otel carbon", 2.5f, 40, 6, 50 );
        v[3] = new MasinaTunsIarba("Makita", "DLM380Z", 1300, "Albastru", 15, "Baterie", "Otel inoxidabil", 36, 38, 5, 40);
        v[4] = new MasinaTunsIarba("Stihl", "RMA 443 C", 2500, "Alb cu portocaliu", 21, "Baterie", "Otel calit", 36, 41, 6, 55 );
        v[5] = new MasinaTunsIarba("Greenworks", "G40LM41", 1400, "Verde", 18, "Baterie", "Aluminiu", 40, 41, 5, 50);
        v[6] = new MasinaTunsIarba("AL-KO", "Classic 4.66 P-A", 1200, "Rosu cu negru", 27, "Benzina", "Otel", 2.7f, 46, 7, 65);
        v[7] = new MasinaTunsIarba("Einhell", "GE-CM 36/47 S HW Li", 2000, "Rosu cu negru", 25, "Baterie", "Otel inoxidabil", 36, 47, 6, 75);
        v[8] = new MasinaTunsIarba("Flymo", "Hover Vac 250", 600, "Portocaliu cu gri", 5.5f, "Electrica", "Plastic durabil", 1400, 25, 4, 15 );
        v[9] = new MasinaTunsIarba("Wolf-Garten", "A 460 A SP HW", 2200, "Rosu cu galben", 35, "Benzina", "Otel inoxidabil", 3.2f, 46, 6, 60 );
    }
    
    private void initVectorMotosapa(){
        u[0] = new Motosapa("Honda", "FG110", 2200, "Roșu", 14, "Benzina", "Manuala", "Freze rotative", "Ergonomic", 3, 100);
        u[1] = new Motosapa("Stihl", "MH 445", 3200, "Portocaliu", 40, "Benzina", "Demaror", "Freze rotative", "Reglabil", 4, 120);
        u[2] = new Motosapa("Makita", "ELM3311", 1900, "Albastru", 12, "Electrică", "Buton electric", "Freze cu lame", "Fix", 3, 105);
        u[3] = new Motosapa("Einhell", "GC-MT 1636/1", 1500, "Roșu", 29, "Benzină", "Manuala", "Freze cu disc", "Pliabil", 3, 115);
        u[4] = new Motosapa("Husqvarna", "TF 230", 4000, "Portocaliu", 66, "Benzină", "Demaror", "Freze grele", "Ergonomic", 5, 140);
        u[5] = new Motosapa("Greenworks", "G-MT40", 2800, "Verde", 17, "Electrică", "Buton electric", "Freze rotative", "Fix", 4, 110);
        u[6] = new Motosapa("Alpina", "A405", 1700, "Alb cu negru", 30, "Benzină", "Manuala", "Freze cu lame", "Reglabil", 3, 125);
        u[7] = new Motosapa("Viking", "HB 560", 4500, "Verde", 48, "Benzină", "Demaror", "Freze grele", "Ergonomic", 4, 135);
        u[8] = new Motosapa("Texas", "Fusion 10TG", 3300, "Negru", 85, "Benzină", "Manuala", "Freze industriale", "Reglabil", 5, 150);
        u[9] = new Motosapa("AgroPro", "MTX 80", 2500, "Albastru", 50, "Diesel", "Demaror", "Freze cu lame", "Pliabil", 4, 130);
    }
    
    private void afiseazaVectoriiCitit(){
        String s = "";
        for(int i = 0 ; i < n1 ; i++){
            s=s+aparate[i]+"\n";
        }
        afisareText4.setText(s);
        s = "";
        for(int i = 0 ; i < n2 ; i++){
            s=s+v[i]+"\n";
        }
        afisareText5.setText(s);
        s = "";
        for(int i = 0 ; i < n3 ; i++){
            s=s+u[i]+"\n";
        }
        afisareText6.setText(s);
    }
    
    private void initCei3VectoriDinFisier(String caleaSpreFisier){
        FileReader fr = null;
        BufferedReader br = null;
        String line = "";
        StringTokenizer st = null;
        try{
            fr = new FileReader(caleaSpreFisier);
            br = new BufferedReader(fr);
            line = br.readLine();
            n1 = Integer.parseInt(line);
            aparate = new Aparat[n1];
            for(int i = 0 ; i < n1 ; i++){
                line = br.readLine();
                st = new StringTokenizer(line,",");
                if(st.countTokens() == 5){
                    aparate[i] = new Aparat();
                    aparate[i].setProducator(st.nextToken());
                    aparate[i].setModel(st.nextToken());
                    aparate[i].setPret(Float.parseFloat(st.nextToken()));
                    aparate[i].setCuloare(st.nextToken());
                    aparate[i].setGreutate(Float.parseFloat(st.nextToken()));
                }else{
                    System.out.println("Problema la formatul continutului din fisier pt aparate");
                }
            }
            line = br.readLine();
            n2 = Integer.parseInt(line);
            v = new MasinaTunsIarba[n2];
            for(int i = 0 ; i < n2 ; i++){
                line = br.readLine();
                st = new StringTokenizer(line,",");
                if(st.countTokens() == 11){
                    v[i] = new MasinaTunsIarba();
                    v[i].setProducator(st.nextToken());
                    v[i].setModel(st.nextToken());
                    v[i].setPret(Float.parseFloat(st.nextToken()));
                    v[i].setCuloare(st.nextToken());
                    v[i].setGreutate(Float.parseFloat(st.nextToken()));
                    v[i].setTipAlimentare(st.nextToken());
                    v[i].setMaterialLama(st.nextToken());
                    v[i].setPutere(Float.parseFloat(st.nextToken()));
                    v[i].setLatimeTaiere(Float.parseFloat(st.nextToken()));
                    v[i].setTrepteTaiere(Integer.parseInt(st.nextToken()));
                    v[i].setVolumCosColector(Float.parseFloat(st.nextToken()));
                }else{
                    System.out.println("Problema la formatul continutului din fisier pt masina de tuns iarba");
                }
            }
            line = br.readLine();
            n3 = Integer.parseInt(line);
            u = new Motosapa[n3];
            for(int i = 0 ; i < n2 ; i++){
                line = br.readLine();
                st = new StringTokenizer(line,",");
                if(st.countTokens() == 11){
                    u[i] = new Motosapa();
                    u[i].setProducator(st.nextToken());
                    u[i].setModel(st.nextToken());
                    u[i].setPret(Float.parseFloat(st.nextToken()));
                    u[i].setCuloare(st.nextToken());
                    u[i].setGreutate(Float.parseFloat(st.nextToken()));
                    u[i].setTipAlimentare(st.nextToken());
                    u[i].setTipPornire(st.nextToken());
                    u[i].setTipTaiere(st.nextToken());
                    u[i].setTipManer(st.nextToken());
                    u[i].setVitezaMaxima(Integer.parseInt(st.nextToken()));
                    u[i].setLungime(Float.parseFloat(st.nextToken()));
                }else{
                    System.out.println("Problema la formatul continutului din fisier pt masina de tuns iarba");
                }
            }
            br.close();
            fr.close();
        }catch(Exception e){
            System.out.println("Eroare la deschiderea/citirea din fisier");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea afisareText;
    private javax.swing.JTextArea afisareText2;
    private javax.swing.JTextArea afisareText3;
    private javax.swing.JTextArea afisareText4;
    private javax.swing.JTextArea afisareText5;
    private javax.swing.JTextArea afisareText6;
    private javax.swing.JButton buttonAparat;
    private javax.swing.JButton buttonMTI;
    private javax.swing.JButton buttonMotosapa;
    private javax.swing.JTextField inputGreutateAparat;
    private javax.swing.JTextField inputGreutateMotosapa;
    private javax.swing.JTextField inputPretAparat;
    private javax.swing.JTextField inputTipAlimentareMTI;
    private javax.swing.JTextField inputTipPornireMotosapa;
    private javax.swing.JTextField inputVolumCosColector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
    int n1,n2,n3;
    Aparat[] aparate;
    MasinaTunsIarba[] v;
    Motosapa[] u;

}
