/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diana.test;
import diana.Suflanta;
import diana.Suflanta;
import javax.swing.JOptionPane;

/**
 *
 * @author da224
 */
public class SuflantaGUI extends javax.swing.JFrame {

    /**
     * Creates new form SuflantaGUI
     */
    public SuflantaGUI() {
        initComponents();
        initVectorSuflanta();
        Afisare.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ButonAfisareMouseClicked(evt);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pretMinimCerut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Afisare = new javax.swing.JButton();
        tipAlimentareCeruta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selectare suflante");

        jLabel2.setText("Introduceti pretul minim: ");

        pretMinimCerut.setToolTipText("Ex. 230");
        pretMinimCerut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretMinimCerutActionPerformed(evt);
            }
        });

        jLabel3.setText("Introduceti tipul de alimentare:");

        Afisare.setText("Afisati  rezultatele");

        tipAlimentareCeruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipAlimentareCerutaActionPerformed(evt);
            }
        });

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pretMinimCerut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipAlimentareCeruta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(Afisare))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pretMinimCerut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipAlimentareCeruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(Afisare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pretMinimCerutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretMinimCerutActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_pretMinimCerutActionPerformed

    private void tipAlimentareCerutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipAlimentareCerutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipAlimentareCerutaActionPerformed

    private void ButonAfisareMouseClicked(java.awt.event.ActionEvent evt){
         try{
        String v = "";
        String tipCerut = tipAlimentareCeruta.getText();
        float pret = Float.parseFloat(pretMinimCerut.getText());
        for(int i = 0 ; i < 10 ; i++){
            if(s[i].getPret() >= pret && s[i].getTipAlimentare().compareTo(tipCerut) == 0)
                v=v+s[i]+'\n';
        }
        Text.setText(v);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Eroare la campurile editate", "Error",JOptionPane.ERROR_MESSAGE);
            System.out.println("eroare la input");
        }
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuflantaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuflantaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuflantaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuflantaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuflantaGUI().setVisible(true);
            }
        });
    }
    
    private void initVectorSuflanta(){
        s[0] = new Suflanta("LittleDomi", "Suflanta aer fara fir", 144.85f, "negru", 0.500f, "acumulator", "electric", (byte) 3, (byte) 68, (short) 74, 7500);
        s[1] = new Suflanta("Steinhaus", "PRO-BL3000", 179.99f, "negru, rosu", 0.650f, "la retea", "electric", (byte) 6, (byte) 120, (short) 92, 9000);
        s[2] = new Suflanta("Goxawee", "M7057", 189.98f, "negru, portocaliu", 0.716f, "acumulator", "electric", (byte) 3, (byte) 120, (short) 150, 8500);
        s[3] = new Suflanta("Heinner", "VSAF002", 209.99f, "negru, verde", 0.690f, "la retea", "electric", (byte) 4, (byte) 90, (short) 84, 8000);
        s[4] = new Suflanta("Bosch", "GSA18V", 259.99f, "albastru, negru", 0.800f, "acumulator", "electric", (byte) 2, (byte) 150, (short) 100, 10000);
        s[5] = new Suflanta("Makita", "UB1103", 239.95f, "albastru", 0.600f, "la retea", "electric", (byte) 3, (byte) 600, (short) 75, 9500);
        s[6] = new Suflanta("Black+Decker", "BV6600", 289.99f, "negru, rosu", 0.900f, "acumulator", "electric", (byte) 4, (byte) 400, (short) 95, 12000);
        s[7] = new Suflanta("DeWalt", "DCE100B", 219.99f, "galben, negru", 0.650f, "acumulator", "electric", (byte) 3, (byte) 180, (short) 82, 8500);
        s[8] = new Suflanta("Ryobi", "RY40440", 279.99f, "verde, negru", 0.750f, "acumulator", "electric", (byte) 5, (byte) 320, (short) 88, 11000);
        s[9] = new Suflanta("Einhell", "TE-CB18/180", 149.99f, "rosu, negru", 0.550f, "acumulator", "electric", (byte) 2, (byte) 180, (short) 60, 7800);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afisare;
    private javax.swing.JTextArea Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pretMinimCerut;
    private javax.swing.JTextField tipAlimentareCeruta;
    // End of variables declaration//GEN-END:variables
    Suflanta[] s = new Suflanta[10];
}
