/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vivi.test;
import vivi.AparatCuratatGeamuri;
import javax.swing.JOptionPane;
/**
 *
 * @author Viv
 */
public class Geamuri extends javax.swing.JFrame {

    /**
     * Creates new form Geamuri
     */
    
    public Geamuri() {
        initComponents();
        initVectorACG();
        Buton.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            AfisareMouseClicked(evt);
        }
    });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        zgomotCitit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        moduriMaximCuratare = new javax.swing.JTextField();
        Buton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Afisare Aparat Curatat Geamuri:");

        jLabel2.setText("Nivel zgomot maxim:");

        zgomotCitit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zgomotCititActionPerformed(evt);
            }
        });

        jLabel3.setText("Numar maxim de moduri de curatare:");

        Buton.setText("Afisare");

        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(Buton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zgomotCitit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moduriMaximCuratare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zgomotCitit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(moduriMaximCuratare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(Buton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AfisareMouseClicked(java.awt.event.ActionEvent evt){
        try{
            String h = "";
            float zgomot = Float.parseFloat(zgomotCitit.getText());
            byte moduriCuratare = Byte.parseByte(moduriMaximCuratare.getText());
            for(int i = 0; i < 10; i++ ){
                if(geamuri[i].getNumarZgomot() <= zgomot && geamuri[i].getNumarModuriCuratare() <= moduriCuratare)
                    h = h + geamuri[i]+'\n';
            }
            Text.setText(h);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Eroare la campurile editate", "Error",JOptionPane.ERROR_MESSAGE);
            System.out.println("eroare la input");
        }
}
    
    
    private void zgomotCititActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zgomotCititActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zgomotCititActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Geamuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Geamuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Geamuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Geamuri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Geamuri().setVisible(true);
            }
        });
    }
private void initVectorACG(){
    geamuri[0] = new AparatCuratatGeamuri("Kärcher", "WindowVac", 899.99f, "Galben", 0.9f, "Microfibră", 3, 60.0f, (byte) 3, "Manual");
        geamuri[1] = new AparatCuratatGeamuri("Bosch", "GlassCleaner", 799.99f, "Verde", 1.1f, "Microfibră", 2, 50.0f, (byte) 2, "Manual");
        geamuri[2] = new AparatCuratatGeamuri("Philips", "GlassExpert", 999.99f, "Albastru", 1.2f, "Silicon", 4, 55.0f, (byte) 4, "Automat");
        geamuri[3] = new AparatCuratatGeamuri("Samsung", "GlassMate", 1199.99f, "Negru", 1.3f, "Textil", 5, 70.0f, (byte) 5, "Automat");
        geamuri[4] = new AparatCuratatGeamuri("Rowenta", "ClearView", 1099.99f, "Gri", 1.5f, "Microfibră", 3, 65.0f, (byte) 3, "Manual");
        geamuri[5] = new AparatCuratatGeamuri("LG", "GlassCare", 799.99f, "Argintiu", 1.4f, "Textil", 4, 60.0f, (byte) 4, "Automat");
        geamuri[6] = new AparatCuratatGeamuri("Black+Decker", "WindowMate", 699.99f, "Negru", 1.0f, "Silicon", 3, 50.0f, (byte) 3, "Manual");
        geamuri[7] = new AparatCuratatGeamuri("Dyson", "GlassWizard", 1599.99f, "Violet", 1.6f, "Microfibră", 6, 75.0f, (byte) 6, "Automat");
        geamuri[8] = new AparatCuratatGeamuri("Bissell", "GlassPro", 899.99f, "Albastru", 1.2f, "Textil", 3, 55.0f, (byte) 3, "Manual");
        geamuri[9] = new AparatCuratatGeamuri("iRobot", "GlassBot", 1299.99f, "Alb", 1.5f, "Silicon", 5, 70.0f, (byte) 5, "Automat");
}
AparatCuratatGeamuri[] geamuri = new AparatCuratatGeamuri[10];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buton;
    private javax.swing.JTextArea Text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField moduriMaximCuratare;
    private javax.swing.JTextField zgomotCitit;
    // End of variables declaration//GEN-END:variables
}
